### ISSUE TITLE
Should I use this library for purposes other than generating test input?

### ISSUE THREAD

**Issue by isomorpheme** [purescript/purescript-gen#5]
I am currently writing an app to generate mazes, and I haven't been able to find something that allows me to generate random values based on a seed (so using `Eff (random :: RANDOM | e)` only for the initial state). `MonadGen` seems to be somewhat appropriate for that, but it seems the only instances are in QuickCheck et al., and I'd prefer not to use a testing library for ordinary functionality. I'm really just looking for something like Haskell's `StdGen`. Is that functionality just not implemented yet, or is that not within the scope of this library?

**Comment by garyb** [comment]
It's primarily intended to provide generators for quickcheck/strongcheck/jack, etc. so that they don't all have to replicate the same code and so that libraries don't have to depend on a particular test framework... but I see no reason at all why you couldn't use it for generating other randomised data too.

We'll not be including a PRNG in here though, so you would need to provide your own instance for `MonadGen` to be able to make use of this stuff. 

Although now we're on the subject I'd be tempted to extract the PRNG from one of the above projects anyway, since the SC and QC RNG has been broken at various times, so having one reliable library for that that could be shared would be a useful thing to have!

**Comment by matthewleon** [comment]
> having one reliable library for that that could be shared would be a useful thing to have!

I actually wrote this lib a while back for just that purpose: https://github.com/matthewleon/purescript-xorshift

It's been a while since I've looked at it, but it might be worth testing against a known good Xorshift32 implementation. In theory, I think it should be an ideal PRNG for QC style libraries: very simple and fast, with predictability.

Might it be worth revisiting and writing a `MonadGen` implementation?
